[workspace]
changelog_update = false

[[package]]
name = "prost-reflect"
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = ["prost-reflect-build", "prost-reflect-derive"] 
